name: emirio_mobile
description: Emirio Mobile App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  http: ^1.2.1
  dio: ^5.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  go_router: ^13.2.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  file_picker: ^8.0.0  # ADD THIS
  image_picker: ^1.0.0

  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.0
  http_parser: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:                    # <-- Commented out until you create the folder
  #   - assets/images/